export const movies = [
  {
    id: 2372,
    movieCode: [null],
    title_en: 'The Paradise of Thorns',
    title_th: 'วิมานหนาม',
    rating: 'ทป.',
    rating_id: 0,
    duration: 125,
    release_date: '2024-08-22',
    sneak_date: '2023-10-03',
    synopsis_th:
      'ทองคำ และ เสก เป็นคู่รักต่างเพศที่ทุ่มเทสร้างชีวิตขึ้นมาด้วยกัน โดยทั้งสองเป็นเจ้าของบ้านและสวนทุเรียนในจังหวัดแม่ฮ่องสอน แต่เรื่องเศร้าก็เกิดขึ้นเมื่อ เสก จากไปอย่างกะทันหันจากอุบัติเหตุ และความจริงที่ว่าทั้งสองไม่เคยแต่งงานกันอย่างถูกกฏหมายของประเทศไทยกลายมาเป็นปัญหาที่ทำให้ ทองคำ ไม่มีสิทธิ์ในทรัพย์สินที่ร่วมสร้างขึ้นมาด้วยกัน\r\n\r\nในตอนนี้บ้านและสวนทุเรียนจึงตกเป็นของแม่ของ เสก ผู้ที่ย้ายเข้ามาอยู่อาศัยพร้อมกับลูกสาวบุญธรรมและคนสวนอีกคนหนึ่ง ทำให้ ทองคำ ต้องต่อสู้เพื่อทวงคืนสิ่งที่เป็นนํ้าพักนํ้าแรงที่เขาและอดีตคนรักร่วมสร้างขึ้นมาด้วยกัน\r\n',
    synopsis_en:
      'Thongkham and Sek, a devoted gay couple, have worked tirelessly to build a life together, including owning a house and a durian orchard in Mae Hong Son. Tragedy strikes when Sek dies suddenly in an accident, revealing that they were never legally married in Thailand, leaving Thongkham with no rights to their assets. The house and orchard now belong to Sek’s mother, who moves in with her adopted daughter Mo and gardener Jingna. Thongkham must now fight to reclaim the fruits of his love and labor.\r\n',
    director: 'Naruebet Kuno',
    actor: 'Pongsakorn Mettarikanont/Worakamol Satoe/Engfa Waraha/Harit Buayoi/Sida Puapimol',
    genre: 'Drama',
    poster_ori: '/uploads/movie/3977/thumb_3977.jpg',
    poster_url: 'https://cdn.majorcineplex.com/uploads/movie/3977/thumb_3977.jpg?v=202408212208',
    widescreen_url:
      'https://cdn.majorcineplex.com/uploads/movie/3977/widescreen_3977.jpg?v=202408211450',
    trailer: 'https://cdn.majorcineplex.com/embed/8582',
    tr_ios: '',
    tr_hd: '',
    tr_sd: '',
    tr_mp4: 'https://cdn.majorcineplex.com/uploads/trailer/rawvideo/8582/8582.mp4',
    priority: '80000',
    now_showing: '1',
    advance_ticket: '1',
    date_update: '2024-08-21 14:50:14',
    show_buyticket: '1',
    trailer_cms_id: '8582',
    trailer_ivx_key: null,
  },
  {
    id: 2377,
    movieCode: [null],
    title_en: 'The Crow',
    title_th: 'อีกาพญายม',
    rating: 'ทป.',
    rating_id: 0,
    duration: 111,
    release_date: '2024-08-22',
    sneak_date: '2024-03-27',
    synopsis_th:
      'เอริก ดราเว่น และ เชลลี่ เว็บสเตอร์ ถูกฆาตกรรมอย่างโหดเหี้ยม เมื่อได้โอกาสที่จะช่วยรักแท้ของเขา เอริก จึงได้เสียสละตัวเองเพื่อตามล้างแค้น โดยเขาได้เดินทางผ่านทั้งโลกของคนเป็นและคนตายเพื่อจะแก้ไขทุกอย่างให้ถูกต้อง\r\n',
    synopsis_en:
      'Soulmates Eric Draven and Shelly Webster are brutally murdered. Given the chance to save his true love by sacrificing himself, Eric sets out to seek revenge, traversing the worlds of the living and the dead to put the wrong things right.\r\n',
    director: 'Rupert Sanders',
    actor: 'Danny Huston/Laura Birn/Bill Skarsgård/FKA Twigs',
    genre: 'Action/Fantasy/Horror',
    poster_ori: '/uploads/movie/4137/thumb_4137.jpg',
    poster_url: 'https://cdn.majorcineplex.com/uploads/movie/4137/thumb_4137.jpg?v=202408212208',
    widescreen_url:
      'https://cdn.majorcineplex.com/uploads/movie/4137/widescreen_4137.jpg?v=202408211450',
    trailer: 'https://cdn.majorcineplex.com/embed/8637',
    tr_ios: '',
    tr_hd: '',
    tr_sd: '',
    tr_mp4: 'https://cdn.majorcineplex.com/uploads/trailer/rawvideo/8637/8637.mp4',
    priority: '79999',
    now_showing: '1',
    advance_ticket: '1',
    date_update: '2024-08-21 14:50:40',
    show_buyticket: '1',
    trailer_cms_id: '8637',
    trailer_ivx_key: null,
  },
  {
    id: 2352,
    movieCode: [null],
    title_en: 'Alien Romulus',
    title_th: 'เอเลี่ยน โรมูลัส',
    rating: 'ทป.',
    rating_id: 0,
    duration: 122,
    release_date: '2024-08-15',
    sneak_date: '2023-08-02',
    synopsis_th:
      'ภาพยนตร์ไซไฟระทึกขวัญเรื่องนี้ นำแฟรนไชส์ที่ประสบความสำเร็จอย่าง “Alien” กลับไปสู่แก่นแท้ของมันอีกครั้ง ในระหว่างที่กำลังเก็บกวาดซากของสถานีอวกาศที่อยู่ไกลออกไป กลุ่มนักบินอวกาศต้องปะทะกับสิ่งมีชีวิตที่น่ากลัวที่สุดในจักรวาล\r\n\r\nภาพยนตร์เรื่องนี้นำแสดงโดย ไคลี สเปนีย์ (“Priscilla”) เดวิด จอนส์สัน (“Agatha Christie’s Murder is Easy”) อาร์ชี เรสักซ์ (“Shadow and Bone”) อิซาเบลา เมอร์เซด (“The Last of Us”) สไปก์ เฟิร์น (“Aftersun”) ไอลีน วู โดยมีเฟเด อัลบาเรซ (“Evil Dead,” “Don’t Breathe”) นั่งแท่นผู้กำกับพร้อมบทที่เขาเขียนร่วมกับ โรโด ซายาเกวซ (“Don’t Breathe 2”) สร้างจากตัวละครโดย แดน โอแบนนอน และ โรนัลด์ ชูเซ็ทท์ Alien: Romulus เอเลี่ยน: โรมูลัส อำนวยการสร้างโดย ริดลีย์ สก็อตต์ (“Napoleon”) ผู้กับดั้งเดิมของ “Alien” และผู้อำนวยการสร้างรวมไปถึงกำกับทั้งซีรีส์ของ “Prometheus” และ “Alien: Covenant,” ไมเคิล พรุส (“Boston Strangler”) และ วอทเทอร์ ฮิลล์ (“Alien”) ร่วมด้วย เฟเด อัลบาเรซ เอลิซาเบธ แคนทิลลอน (“Charlie’s Angels”) เบรนท์ โอคอนเนอร์ (“Bullet Train”) และ ทอม โมรัน(“Unstoppable”) นั่งแท่นผู้อำนวยการสร้างฝ่ายบริหาร\r\n',
    synopsis_en:
      'The sci-fi/horror-thriller takes the phenomenally successful “Alien” franchise back to its roots: While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.\r\n\r\nThe film stars Cailee Spaeny (“Priscilla”), David Jonsson (“Agatha Christie’s Murder is Easy”), Archie Renaux (“Shadow and Bone”), Isabela Merced (“The Last of Us”), Spike Fearn (“Aftersun”), Aileen Wu. Fede Alvarez (“Evil Dead,” “Don’t Breathe”) directs from a screenplay he wrote with frequent collaborator Rodo Sayagues (“Don’t Breathe 2”) based on characters created by Dan O’Bannon and Ronald Shusett. “Alien: Romulus” is produced by Ridley Scott (“Napoleon”), who directed the original “Alien” and produced and directed the series’ entries “Prometheus” and “Alien: Covenant,” Michael Pruss (“Boston Strangler”), and Walter Hill (“Alien”), with Fede 2 Alvarez, Elizabeth Cantillon (“Charlie’s Angels”), Brent O’Connor (“Bullet Train”), and Tom Moran (“Unstoppable”) serving as executive producers.\r\n',
    director: 'Fede Álvarez',
    actor: 'Cailee Spaeny/Isabela Merced/Archie Renaux/David Jonsson/Aileen Wu/Spike Fearn',
    genre: 'Horror/Sci-Fi/Thriller',
    poster_ori: '/uploads/movie/3933/thumb_3933.jpg',
    poster_url: 'https://cdn.majorcineplex.com/uploads/movie/3933/thumb_3933.jpg?v=202408212208',
    widescreen_url:
      'https://cdn.majorcineplex.com/uploads/movie/3933/widescreen_3933.jpg?v=202408211451',
    trailer: 'https://cdn.majorcineplex.com/embed/8588',
    tr_ios: '',
    tr_hd: '',
    tr_sd: '',
    tr_mp4: 'https://cdn.majorcineplex.com/uploads/trailer/rawvideo/8588/8588.mp4',
    priority: '79000',
    now_showing: '1',
    advance_ticket: '0',
    date_update: '2024-08-21 14:51:42',
    show_buyticket: '1',
    trailer_cms_id: '8588',
    trailer_ivx_key: null,
  },
  {
    id: 2371,
    movieCode: [null],
    title_en: 'Subservience',
    title_th: 'เอไอร้อนรัก',
    rating: 'ทป.',
    rating_id: 0,
    duration: 97,
    release_date: '2024-08-15',
    sneak_date: '2024-07-17',
    synopsis_th:
      '"ยินดีต้อนรับสู่โลกอนาคต เมื่อมนุษย์สามารถจ้างหุ่นยนต์เอไอให้คอยรับใช้ได้ แต่เมื่อ "นิค" ชายหนุ่มผู้ประสบปัญหาการจัดการชีวิต ได้พลาดท่าไปหลงเสน่ห์เกินต้านของ  "อลิซ" เอไอสาวสวย จนเกิดมีสัมพันธ์อันเร่าร้อน ทำให้เธอผูกพันกับเขา ถึงขั้นพร้อมกำจัดทุกคนที่เธอพิจารณาว่าเป็นภัยคุกคามต่อนิค ไม่เว้นแม้กระทั่งครอบครัวของเขา บัดนี้เทคโนโลยีล้ำสมัย กำลังอัปเกรดสู่ความสยองเกินต้านทาน"\r\n',
    synopsis_en:
      'Follows a struggling father who purchases a domestic SIM to help care for his house and family, unaware she will gain awareness and turn deadly.\r\n',
    director: 'S.K. Dale',
    actor:
      'Megan Fox/Kate Nichols/Madeline Zima/Michele Morrone/Atanas Srebrev/Andrew Whipp/Matilda Firth',
    genre: 'Sci-Fi/Thriller',
    poster_ori: '/uploads/movie/4255/thumb_4255.jpg',
    poster_url: 'https://cdn.majorcineplex.com/uploads/movie/4255/thumb_4255.jpg?v=202408212208',
    widescreen_url:
      'https://cdn.majorcineplex.com/uploads/movie/4255/widescreen_4255.jpg?v=202408151534',
    trailer: 'https://cdn.majorcineplex.com/embed/8649',
    tr_ios: '',
    tr_hd: '',
    tr_sd: '',
    tr_mp4: 'https://cdn.majorcineplex.com/uploads/trailer/rawvideo/8649/8649.mp4',
    priority: '79000',
    now_showing: '1',
    advance_ticket: '0',
    date_update: '2024-08-15 15:34:03',
    show_buyticket: '1',
    trailer_cms_id: '8649',
    trailer_ivx_key: null,
  },
  {
    id: 2374,
    movieCode: [null],
    title_en: 'Blink Twice',
    title_th: 'บลิงก์ ทไวซ์ ซิกอันตราย',
    rating: 'ทป.',
    rating_id: 0,
    duration: 102,
    release_date: '2024-08-22',
    sneak_date: '2024-03-27',
    synopsis_th:
      'เมื่อมหาเศรษฐีพันล้าน สเลเทอร์ คิง (แชนนิ่ง เททัม) ได้พบกับบริกรสาว ฟริดา ที่งานเลี้ยงเพื่อการระดมทุนของเขา ความสัมพันธ์ของทั้งสองก็รุดหน้าไปอย่างรวดเร็ว โดยเขาได้ชวนให้เธอมาร่วมงานเลี้ยงบนเกาะส่วนตัวแห่งหนึ่ง แต่ในคำ่คืนอันสนุกสุดเหวี่ยงที่ใครไม่อยากให้จบลงนี้ บางสิ่งที่แปลกประหลาดที่ได้เกิดขึ้น ทำให้ ฟริดา เริ่มตั้งคำถามกับสิ่งที่เกิดขึ้น และเธอต้องเปิดโปงความจริงที่ถูกซ่อนเอาไว้ ถ้าหากว่าเธอต้องการจะมีชีวิตรอดออกไปจากงานเลี้ยงในครั้งนี้\r\n',
    synopsis_en:
      "When tech billionaire Slater King (Channing Tatum) meets cocktail waitress Frida (Naomi Ackie) at his fundraising gala, sparks fly. He invites her to join him and his friends on a dream vacation on his private island. It's paradise. Wild nights blend into sun soaked days and everyone's having a great time. No one wants this trip to end, but as strange things start to happen, Frida begins to question her reality. There is something wrong with this place. She'll have to uncover the truth if she wants to make it out of this party alive.\r\n",
    director: 'Zoë Kravitz',
    actor:
      'Channing Tatum/Kyle MacLachlan/Naomi Ackie/Christian Slater/Adria Arjona/Alia Shawkat/Simon Rex/Haley Joel Osment/Geena Davis',
    genre: 'Crime/Thriller',
    poster_ori: '/uploads/movie/4133/thumb_4133.jpg',
    poster_url: 'https://cdn.majorcineplex.com/uploads/movie/4133/thumb_4133.jpg?v=202408212208',
    widescreen_url: null,
    trailer: 'https://cdn.majorcineplex.com/embed/8646',
    tr_ios: '',
    tr_hd: '',
    tr_sd: '',
    tr_mp4: 'https://cdn.majorcineplex.com/uploads/trailer/rawvideo/8646/8646.mp4',
    priority: '78000',
    now_showing: '1',
    advance_ticket: '1',
    date_update: '2024-08-21 14:52:12',
    show_buyticket: '1',
    trailer_cms_id: '8646',
    trailer_ivx_key: null,
  },
  {
    id: 2367,
    movieCode: [null],
    title_en: 'Kinds of Kindness',
    title_th: 'Kinds of Kindness',
    rating: 'ทป.',
    rating_id: 0,
    duration: 164,
    release_date: '2024-08-22',
    sneak_date: '2024-04-30',
    synopsis_th:
      'ชายคนหนึ่งที่พยายามจะหลีกหนีออกมาจากเส้นทางที่ถูกกำหนดไว้ของเขา, เจ้าหน้าที่ตำรวจคนหนึ่งที่ตั้งข้อสงสัยในพฤติกรรมของภรรยาของเขา หลังจากที่เธอกลับมาจากเหตุการณ์ที่เธอควรจะจมนํ้า และหญิงสาวคนหนึ่งที่ตั้งใจที่จะค้นหาใครสักคนที่ถูกทำนายไว้ว่าจะกลายมาเป็นผู้นำทางจิตวิญญาณที่มีชื่อเสียง ทั้งสามตัวละครจะเข้ามาพบเจอกันในภาพยนตร์เรื่องนี้\r\n',
    synopsis_en:
      "A man seeks to break free from his predetermined path, a cop questions his wife's demeanor after her return from a supposed drowning and a woman's quest to locate an extraordinary individual prophesied to become a renowned spiritual guide.\r\n",
    director: 'Yorgos Lanthimos',
    actor:
      'Willem Dafoe/Emma Stone/Hong Chau/Jesse Plemons/Mamoudou Athie/Hunter Schafer/Margaret Qualley/Joe Alwyn',
    genre: 'Comedy/Drama',
    poster_ori: '/uploads/movie/4166/thumb_4166.jpg',
    poster_url: 'https://cdn.majorcineplex.com/uploads/movie/4166/thumb_4166.jpg?v=202408212208',
    widescreen_url:
      'https://cdn.majorcineplex.com/uploads/movie/4166/widescreen_4166.jpg?v=202408211452',
    trailer: 'https://cdn.majorcineplex.com/embed/8600',
    tr_ios: '',
    tr_hd: '',
    tr_sd: '',
    tr_mp4: 'https://cdn.majorcineplex.com/uploads/trailer/rawvideo/8600/8600.mp4',
    priority: '77000',
    now_showing: '1',
    advance_ticket: '1',
    date_update: '2024-08-21 14:52:40',
    show_buyticket: '1',
    trailer_cms_id: '8600',
    trailer_ivx_key: null,
  },
];
